{{- if .Values.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-registry
  labels:
    {{- include "generic.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "generic.dockerconfigjson" . }}
{{- end }}
